language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - "pip install coveralls nose"
  - "pip install -r requirements.txt"
script: coverage run --source=vaquero setup.py nosetests
after_success: coveralls
