language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
install:
  - "pip install coveralls nose"
  - "pip install -r requirements.txt"
script: coverage run --source=vaquero setup.py nosetests
after_success: coveralls